### ISSUE TITLE
Be able to change comment label

### ISSUE THREAD

**Issue by danielgomezrico** [MeilCli/danger-action#340]
## Feature description

The comment that is done on the PR have the label "github-actions" 
![image](https://user-images.githubusercontent.com/76348/149450309-bbd29f62-3b0b-44e5-a7be-e411885273c6.png)

Can this name be parameterized, so we can have different ones?

**Comment by MeilCli** [comment]
@danielgomezrico 
Sorry, I don't know to change bot name for github-actions app. 
How do we parameterize the name?

**Comment by MeilCli** [comment]
I know one way to change name, it is to use different github token

**Comment by danielgomezrico** [comment]
What do you mean by a different github token? where?

I see there is a param `danger_id`, what is the purpose of that?

**Comment by MeilCli** [comment]
@danielgomezrico 
The Icon and name of the issue comment posted by Danger is the one set in GitHub User/Apps.
To change these, your'll have to use a different account.

ref:
- if use GitHub User:  Token type is Personal Access Token(PAT)
  - https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
- if use GitHub Apps: Token type is app token
  - https://docs.github.com/en/developers/apps/building-github-apps/creating-a-github-app
  - I'm recommend you use this action: https://github.com/tibdex/github-app-token

Once the Token is prepared, set it in the DANGER_GITHUB_API_TOKEN environment variable.

And `danger_id` param purpose is to identify multiple danger instance at same PR. So I usually don't use this parameter.

**Comment by MeilCli** [comment]
@danielgomezrico 
How are things going after that?

**Comment by danielgomezrico** [comment]
I haven't tried that 🙈 but since this is not a feature feasible for this action I will close the issue.
