### ISSUE TITLE
Documentation that this action does not support pull requests from fork repositories.

### ISSUE THREAD

**Issue by crazyoptimist** [MeilCli/danger-action#609]
Pull requests from forks don't have access to repo or org secrets. See https://github.com/danger/danger-js/blob/main/source/ci_source/providers/GitHubActions.ts#L152

Would be fair if you have a documentation saying it doesn't support PRs from forks.

**Comment by MeilCli** [comment]
@crazyoptimist 
Thanks your issue reporting.
I added attention this case to README.

If you still have problems, please reopen this issue.

**Comment by crazyoptimist** [comment]
Well done. Thanks!
