### ISSUE TITLE
issues on Apple Silicon

### ISSUE THREAD

**Issue by reshadf** [MeilCli/danger-action#819]
[Please easy english or easy japanese]
## Description
When running the action inside self hosted Mac mini m2 I get the following:
`vendor/bundle/ruby/3.2.0/gems/ffi-1.15.5/lib/ffi_c.bundle' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')`

Is there a way to fix this? 
## Environment
Apple Silicon m2

**Comment by MeilCli** [comment]
It is not this actions's problem.
https://stackoverflow.com/questions/71882029/mach-o-file-but-is-an-incompatible-architecture-have-arm64-need-x86-64-i
https://stackoverflow.com/questions/66644365/cocoapods-on-m1-apple-silicon-fails-with-ffi-wrong-architecture
