### ISSUE TITLE
Request for Node.js 20 support

### ISSUE THREAD

**Issue by KoheiMoroi** [MeilCli/danger-action#954]
[Please easy english or easy japanese]

## Feature description
I am writing to inform you that Node.js 16 in GitHub Actions will soon reach its end of support by Spring 2024.
As a result, we are looking to upgrade your workflows to e newer version in order to ensure continued performance and security.
We would be grateful if you could plan accordingly for this upgrade.
Thank you.

https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

**Comment by MeilCli** [comment]
Sorry delayed response. I just start the updating now. Please wait few hours.

**Comment by MeilCli** [comment]
https://github.com/MeilCli/danger-action/releases/tag/v6.0.0
I have updated.

**Comment by KoheiMoroi** [comment]
Thank you for the update!
